### PR TITLE
Feature/create index page

### PR DESCRIPTION
**Pull request by kamalogudah**
## What is the Purpose?
This adds an Index Page to the PR sample app.
## What was the approach?
Presently not the best implementation as I have style in the same page, but looking for a way to structure styles on plug apps.
## Are there any concerns to addressed further before or after merging this PR?
The page can be further improved later, this just is placeholders.

## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
List of issues addressed by this PR.

### CODE REVIEW

**Comment by manuelgeek** [comment]
@kamalogudah ,This is good. We truly need this. was just thinking of the contents we need there. This we can discuss on later. But i was thinking of if we can maybe render the `readme.md` to be html, cause it will pretty much cover everything. just a though.
And since it's a simple page, I don't think I personally mind having the css there, unless the files grows, it's something we can check on in future, but no harm if you work on it

**Review by manuelgeek — APPROVED** [review]

**Comment by manuelgeek** [comment]
@kamalogudah , one more thing, are the contents of the page needed to be in this PR, or it's something we can discuss about later?

**Comment by kamalogudah** [comment]
> @kamalogudah , one more thing, are the contents of the page needed to be in this PR, or it's something we can discuss about later?
Was thinking of Linking the different endpoints from this page, so once you are on a particular page eg. USSD we can have info on its implementation since the sample app, unlike the library, will not have documentation to explain how it works.

**Comment by manuelgeek** [comment]
> > @kamalogudah , one more thing, are the contents of the page needed to be in this PR, or it's something we can discuss about later?
> > Was thinking of Linking the different endpoints from this page, so once you are on a particular page eg. USSD we can have info on its implementation since the sample app, unlike the library, will not have documentation to explain how it works.



That is also fine, i hadn't thought about it . That can will work

**Comment by manuelgeek** [comment]
The PR is 8 days old, seems there is no more reactions coming soon

**Pull request merged**
